name: Run tests

on: [pull_request]

jobs:
    prettier:
        name: Prettier
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: '16.x'

            - name: Install dependencies
              run: npm install

            - name: Run prettier
              run: npx prettier --check **/*.ts

    test:
        name: Test
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: '16.x'

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm run test
